<?php
/**
 * "Jump to comments" link rewriter.
 *
 * WordPress builds the post-meta comments link with an anchor that
 * targets the original comments markup (`#comments`). When lazy-loading
 * replaces that markup with our placeholder, the old anchor is no
 * longer in the DOM and the jump link scrolls to nothing.
 *
 * This class rewrites every `get_comments_link()` URL to instead point
 * at the placeholder's anchor (`#llc-comments`) so the link continues
 * to work — and the front-end script also reads the hash on load and
 * triggers an immediate fetch when it matches.
 *
 * @package LazyComments
 */

declare( strict_types = 1 );

namespace DuckDev\LazyComments\Front;

// If this file is called directly, abort.
defined( 'ABSPATH' ) || exit;

use DuckDev\LazyComments\Utils\Singleton;

/**
 * Class LinkRewriter
 *
 * @since   2.0.0
 * @package DuckDev\LazyComments\Front
 */
class LinkRewriter extends Singleton {

	/**
	 * Hook priority for the `get_comments_link` filter.
	 *
	 * Runs late (100) so it wins against theme- and plugin-level filters.
	 *
	 * @since 2.0.0
	 */
	const FILTER_PRIORITY = 100;

	/**
	 * Register the comments-link filter.
	 *
	 * @since 2.0.0
	 *
	 * @return void
	 */
	protected function init(): void {
		add_filter( 'get_comments_link', array( $this, 'rewrite' ), self::FILTER_PRIORITY, 2 );
	}

	/**
	 * Filter callback: rewrite the comments link to target our placeholder.
	 *
	 * @since 2.0.0
	 *
	 * @param string $link    Original comments link generated by WordPress.
	 * @param int    $post_id ID of the post the link points at.
	 *
	 * @return string Either the rewritten URL or the original (when
	 *                lazy-loading is not eligible).
	 */
	public function rewrite( $link, $post_id ): string {
		if ( Detector::instance()->can_lazy_load() ) {
			return get_permalink( (int) $post_id ) . '#' . Renderer::ANCHOR_ID;
		}

		return (string) $link;
	}
}
