<?php
/**
 * Plugin information and lifecycle class.
 *
 * Holds static plugin metadata and handles activation/deactivation.
 *
 * @package LazyComments
 */

namespace DuckDev\LazyComments;

// If this file is called directly, abort.
defined( 'WPINC' ) || die;

/**
 * Class Plugin
 *
 * @since   2.0.0
 * @package DuckDev\LazyComments
 */
class Plugin {

	/**
	 * Plugin slug (matches the wp.org slug).
	 *
	 * @since 2.0.0
	 */
	const SLUG = 'lazy-load-for-comments';

	/**
	 * Admin settings page slug.
	 *
	 * @since 2.0.0
	 */
	const PAGE = 'lazy-load-for-comments';

	/**
	 * Get the human readable plugin name.
	 *
	 * @since 2.0.0
	 *
	 * @return string
	 */
	public static function name() {
		return 'Lazy Load for Comments';
	}

	/**
	 * Get the current plugin version.
	 *
	 * @since 2.0.0
	 *
	 * @return string
	 */
	public static function version() {
		return LLC_VERSION;
	}

	/**
	 * Get the settings page URL.
	 *
	 * @since 2.0.0
	 *
	 * @return string
	 */
	public static function settings_url() {
		return admin_url( 'edit-comments.php?page=' . self::PAGE );
	}

	/**
	 * Get the admin screen ID of the settings page.
	 *
	 * The settings page is a sub menu of the Comments menu, so the
	 * screen ID is prefixed with `comments_page_`.
	 *
	 * @since 2.0.0
	 *
	 * @return string
	 */
	public static function screen_id() {
		return 'comments_page_' . self::PAGE;
	}

	/**
	 * Get build metadata for a compiled asset.
	 *
	 * Reads the `*.asset.php` file generated by `@wordpress/scripts`,
	 * which contains the script dependencies and a content hash.
	 *
	 * @since 2.0.0
	 *
	 * @param string $handle Asset handle (e.g. 'settings', 'frontend').
	 *
	 * @return array{dependencies: string[], version: string}
	 */
	public static function asset( $handle ) {
		$file = LLC_DIR . 'app/assets/' . $handle . '.asset.php';
		$data = is_readable( $file ) ? require $file : array();

		return wp_parse_args(
			(array) $data,
			array(
				'dependencies' => array(),
				'version'      => LLC_VERSION,
			)
		);
	}

	/**
	 * Run plugin activation tasks.
	 *
	 * @since 2.0.0
	 *
	 * @return void
	 */
	public static function activate() {
		// Make sure default settings exist (also migrates legacy option).
		Settings::instance()->maybe_migrate();

		/**
		 * Action hook fired after the plugin is activated.
		 *
		 * @since 2.0.0
		 */
		do_action( 'lazy_load_for_comments_activated' );
	}

	/**
	 * Run plugin deactivation tasks.
	 *
	 * @since 2.0.0
	 *
	 * @return void
	 */
	public static function deactivate() {
		/**
		 * Action hook fired after the plugin is deactivated.
		 *
		 * @since 2.0.0
		 */
		do_action( 'lazy_load_for_comments_deactivated' );
	}
}
